spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: preventRestartJob
#      enabled: false
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/Study/Practice/spring/springbatch
      username: sa
      password:
      driver-class-name: org.h2.Driver